**Numpy**

* Matrix operations and arrays: Used for handling arrays and matrices in data processing.
* Deep Learning: Works with stored data structures, commonly used in ML/AI pipelines.
* Performance: Numpy is faster compared to Pandas for many array-related operations.

In [55]:
import numpy as np

In [ ]:
# Create a numpy array from a list
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
np_lst = np.array(lst)
print(np_lst)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
# Check the shape of the array
np_lst.shape  # (15,) signifies a 15x1 vector

(15,)

In [ ]:
# tek boyutlu matrisi iki böyutlu matrise çevirmek reshape()
# 15x1'lik bir arrayi 3x5'lik matrise çevirme
np_lst2 = np_lst.reshape(3,5)
np_lst2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# Inspect array properties
print("Shape: ", np_lst2.shape)  # Dimensions of the array
print("Dimension: ", np_lst2.ndim)  # Number of dimensions
print("Size: ", np_lst2.size)  # Total elements in the array
print("Type: ", type(np_lst2))  # Data type of the array

Shape:  (3, 5)
Dimension:  2
Size:  15
Type:  <class 'numpy.ndarray'>


In [ ]:
# Create a 2D array manually
arr2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 7, 5]])
print(arr2D)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 5]]


In [ ]:
# Creating arrays filled with zeros (for neural network projects)
zero_array = np.zeros((3, 4))
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Creating arrays filled with ones
one_array = np.ones((3, 4))
print(one_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Create an empty array
empty_array = np.empty((2, 4))  # Values are uninitialized
print(empty_array)

[[4.72749488e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [ ]:
# Create arrays with a range of values using `arange`
range_array = np.arange(10, 50, 5)  # From 10 to 50 (exclusive) with a step of 5
print(range_array)

[10 15 20 25 30 35 40 45]


In [ ]:
# Create evenly spaced values between two limits with `linspace`
linspace_array = np.linspace(10, 50, 5)  # Divides 10-50 into 5 equal parts
print(linspace_array)
print(len(linspace_array))

[10. 20. 30. 40. 50.]
5


**Basic Numpy Operations**

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
# Basic operations on arrays
print("Addition: ", a + b)
print("Subtraction: ", a - b)
print("Element-wise squaring: ", a**2)

Addition:  [5 7 9]
Subtraction:  [-3 -3 -3]
Element-wise squaring:  [1 4 9]


In [ ]:
# Filtering values in an array
filter_condition = a < 2  # Identifies elements in `a` less than 2
filter_condition

array([ True, False, False])

In [ ]:
# Dot product of two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Dot product: ", a.dot(b))

Dot product:  32


In [ ]:
# Dot product with matrix transpose
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[4, 5, 6], [1, 2, 3]])
print(a.dot(b.T))

[[32 14]
 [77 32]]


In [ ]:
# Sum of array elements
print(sum(a))  # Row-wise sum
print(np.sum(a))  # Overall sum

[5 7 9]
21


In [ ]:
# Maximum and minimum values in an array
print("Max: ", a.max())
print("Max: ", np.max(a))
print("Min: ", a.min())
print("Min: ", np.min(a))

Max:  6
Max:  6
Min:  1
Min:  1


In [ ]:
# Summing along rows and columns
print("Row sums: ", a.sum(axis=1))
print("Column sums: ", a.sum(axis=0))

Row sums:  [ 6 15]
Column sums:  [5 7 9]


In [ ]:
# Squaring values in an array
print("Squared: ", np.square(a))
print("Squared (alternate): ", a**2)

Squared:  [[ 1  4  9]
 [16 25 36]]
Squared (alternate):  [[ 1  4  9]
 [16 25 36]]


In [ ]:
# Generate random numbers
random_array = np.random.random((3, 3))  # Random numbers between 0 and 1
print(random_array)

[[0.48337203 0.82397462 0.90134458]
 [0.22239664 0.59776841 0.14262309]
 [0.22056878 0.15322034 0.30227768]]


In [ ]:
normal_random_array = np.random.normal(0, 1, 5)  # Normal distribution (mean=0, std=1)
print(normal_random_array)

[ 0.05803358 -0.44720738 -0.27637756  0.17711169 -0.53438125]


**Indexing and Slicing**

In [ ]:
# 1D array indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[0])  # First element
print(arr[:4])  # First four elements
print(arr[::-1])  # Reverse the array

1
[1 2 3 4]
[7 6 5 4 3 2 1]


In [ ]:
# 2D array indexing
arr2D = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])

print(arr2D[1, 2])  # Element at 1st row, 2nd column
print(arr2D[1, (0, 1, 2, 3, 4)])  # Elements in row 1 and selected columns
print(arr2D[:, 2:4])  # All rows, columns 2 to 4
print(arr2D[-1, :])  # Last row

8
[ 6  7  8  9 10]
[[3 4]
 [8 9]]
[ 6  7  8  9 10]


**Shape Manipulation**

In [ ]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
dizi2D_shape = dizi2D.shape
dizi2D_shape

(3, 3)

In [ ]:
# Reshape the array
reshaped = arr2D.reshape(9, 1)
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
# ravel the array (used in TensorFlow as "flatten")
arr2D.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Transpose the array
arr2D.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
"""
1) Create a 2D array A with dimensions (3, 5).
2) Create a 1D array B with 15 elements.
3) Reshape the array B into a (3, 5) matrix.
4) Calculate C = A + B.
5) Create two (3, 5) matrices, D using linspace and E using arange.
Compute F = D + E.
Multiply each element of C and F element-wise using a for loop, and reduce the result into a (15, 1) array G.
Reshape C and F into (15, 1). Then, iterate through these arrays by summing the first element of C with the last element of F and so on.
If the sum is greater than 1, append it to a list named G1; otherwise, append it to a list named G2.
"""

In [56]:
# Initial arrays
A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])

B = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

# Reshape B to match A's shape
B_reshaped = B.reshape(3, 5)

# Add A and reshaped B
C = A + B_reshaped
print("C:\n", C)

# Create matrices D and E
D = np.linspace(1, 15, 15).reshape(3, 5)  # Create a matrix using linspace
print("D:\n", D)

E = np.arange(1, 16).reshape(3, 5)  # Create a matrix using arange
print("E:\n", E)

# Add D and E
F = D + E
print("F:\n", F)

# Calculate element-wise product of C and F, and reshape to (15, 1)
G = []
for i in range(C.shape[0]):  # Loop through rows of C
    for j in range(C.shape[1]):  # Loop through columns of C
        G.append(C[i, j] * F[i, j])  # Multiply corresponding elements and append to G
G = np.array(G).reshape(15, 1)
print("G:\n", G)

# Reshape C and F to (15, 1)
C_reshaped = C.reshape(15, 1)
F_reshaped = F.reshape(15, 1)

# Iterate over C and F to compute sums
G1 = []  # List for values where the sum is greater than 1
G2 = []  # List for values where the sum is less than or equal to 1

for i in range(C_reshaped.shape[0]):
    total = C_reshaped[i, 0] + F_reshaped[C_reshaped.shape[0] - 1 - i, 0]  # Add elements from opposite ends
    if total > 1:
        G1.append(total)  # Add to G1 if the sum is greater than 1
    else:
        G2.append(total)  # Add to G2 if the sum is less than or equal to 1

print("G1:", G1)
print("G2:", G2)

C:
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]
D:
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]
E:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
F:
 [[ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]]
G:
 [[  4.]
 [ 16.]
 [ 36.]
 [ 64.]
 [100.]
 [144.]
 [196.]
 [256.]
 [324.]
 [400.]
 [484.]
 [576.]
 [676.]
 [784.]
 [900.]]
G1: [32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0]
G2: []
Vertical Stacking:
 [[ 1  2]
 [ 3  4]
 [-1 -2]
 [-3 -4]]
Horizontal Stacking:
 [[ 1  2 -1 -2]
 [ 3  4 -3 -4]]
3 Array Vertical Stacking:
 [[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]
3 Array Horizontal Stacking:
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


**Stacking**

In [57]:
# Stacking examples
dizi1 = np.array([[1, 2], [3, 4]])
dizi2 = np.array([[-1, -2], [-3, -4]])

In [58]:
# Vertical stack
dizi_dikey = np.vstack((dizi1, dizi2))
print("Vertical Stacking:\n", dizi_dikey)

Vertical Stacking:
 [[ 1  2]
 [ 3  4]
 [-1 -2]
 [-3 -4]]


In [59]:
# Horizontal stack
dizi_yatay = np.hstack((dizi1, dizi2))
print("Horizontal Stacking:\n", dizi_yatay)

Horizontal Stacking:
 [[ 1  2 -1 -2]
 [ 3  4 -3 -4]]


In [63]:
# Stacking 3 arrays vertically
vertical_stack = np.vstack((dizi1, dizi1, dizi1))  # Stack vertically
print("3 Array Vertical Stacking:\n", vertical_stack)

3 Array Vertical Stacking:
 [[1 2]
 [3 4]
 [1 2]
 [3 4]
 [1 2]
 [3 4]]


In [64]:
# Stacking 3 arrays horizontally
horizontal_stack = np.hstack((dizi1, dizi1, dizi1))  # Stack horizontally
print("3 Array Horizontal Stacking:\n", horizontal_stack)

3 Array Horizontal Stacking:
 [[1 2 1 2 1 2]
 [3 4 3 4 3 4]]
